{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cookiemonster-cm-nodeexec
  namespace: {{ $envAll.Release.Namespace }}
  labels:
    component: cookiemonster
data:
  test-exec-random.json: |-
    {
      "target": "",
      "commands": [
        {
          "command": "hostname"
        },
        {
          "command": "sleep",
          "parameters": [
            "10"
          ]
        },
        {
          "command": "df",
          "parameters": [
            "-h"
          ]
        }
      ]
    }
  test-exec-single.json: |-
    {
      "target": "cn02.k4.stg.taco",
      "commands": [
        {
          "command": "hostname"
        },
        {
          "command": "date"
        },
        {
          "command": "ls",
          "parameters": [
            "-l"
          ]
        }
      ]
    }
  test-exec-all.json: |-
    {
      "target": "all",
      "commands": [
        {
          "command": "hostname"
        },
        {
          "command": "whoami"
        },
        {
          "command": "ps",
          "parameters": [
            "aux"
          ]
        }
      ]
    }
